In [1]:
import numpy as np
def lu_decomposition(A):
    n=len(A)
    L=np.zeros((n,n))
    U=np.zeros((n,n))
    for i in range(n):
        for k in range(i,n):
            sum_upper=0
            for j in range(i):
                sum_upper+=L[i][j]*U[j][k]
            U[i][k]=A[i][k]-sum_upper
        L[i][i]=1
        for k in range(i+1,n):
            sum_lower=0
            for j in range(i):
                sum_lower+=L[k][j]*U[j][i]
            L[k][i]=(A[k][i]-sum_lower)/U[i][i]
    return L,U
def forward_substitution(L,b):
    n=len(L)
    y=np.zeros(n)
    for i in range(n):
        sum_value=0
        for j in range(i):
            sum_value+=L[i][j]*y[j]
        y[i]=(b[i]-sum_value)/L[i][i]
    return y
def backward_substitution(U,y):
    n=len(U)
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        sum_value=0
        for j in range(i+1,n):
            sum_value+=U[i][j]*x[j]
        x[i]=(y[i]-sum_value)/U[i][i]
    return x
A=np.array([[2,-1,-2],[-4,6,3],[-4,-2,5]],dtype=float)
b=np.array([-2,9,10],dtype=float)
L,U=lu_decomposition(A)
y=forward_substitution(L,b)
x=backward_substitution(U,y)
print("Matrix A:")
print(A)
print("\nLower Triangular Matrix L:")
print(L)
print("\nUpper Triangular Matrix U:")
print(U)
print("\nIntermediate Solution y:")
print(y)
print("\nFinal Solution x:")
print(x)

Matrix A:
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  5.]]

Lower Triangular Matrix L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]

Upper Triangular Matrix U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  0.]]

Intermediate Solution y:
[-2.  5. 11.]

Final Solution x:
[inf inf inf]


/tmp/ipykernel_538/502927145.py:35: RuntimeWarning: divide by zero encountered in scalar divide
  x[i]=(y[i]-sum_value)/U[i][i]
